name: Tests

on:
  [push, pull_request]

defaults:
  run:
    shell: bash -l {0}

jobs:
  pytests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: qutip/qutip
        path: qutip
        ref: master
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: test
        environment-file: test_environment.yml
        auto-activate-base: false
        auto-update-conda: true

    - name: Install QuTiP
      run: |
        pip install -r qutip/requirements.txt
        python qutip/setup.py develop
    - name: Run tests
      timeout-minutes: 60
      run: |
        conda install jupyter nbformat nbconvert
        jupyter kernel &
        conda install pytest nbmake
        pytest --nbmake examples/nonmarkov-transfer-tensor-method.ipynb
